//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FontAwesome6
{
	/// <summary>
	/// FontAwesome by Dave Gandy (@davegandy)
	///	The iconic SVG, font, and CSS toolkit
	///	License https://fontawesome.com/license (C#: MIT License)
	/// Version: 6.4.0 
	/// </summary>
	public enum EFontAwesomeStyle
	{
		/// <summary>
		/// This Style is used as an undefined state.
		/// </summary>
		None,		
		/// <summary>
		/// FontAwesome Solid Style
		/// </summary>
		Solid,
		/// <summary>
		/// FontAwesome Brands Style
		/// </summary>
		Brands,
		/// <summary>
		/// FontAwesome Regular Style
		/// </summary>
		Regular,
		/// <summary>
		/// FontAwesome Duotone Style
		/// </summary>
		Duotone,
		/// <summary>
		/// FontAwesome Light Style
		/// </summary>
		Light,
		/// <summary>
		/// FontAwesome Thin Style
		/// </summary>
		Thin,
    }
}